import { ServicioData } from "../../../domain/entities/Servicio";

export const BARBA: ServicioData[] = [
  {
    name: "Rasurado con Navaja",
    description: "Afeitado clásico con navaja de barbero. Incluye toalla caliente, preparación con aceites, rasurado preciso en múltiples pasadas y loción post-afeitado.",
    price: 18000,
    category: "Barba",
    imageUrls: ["https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80&auto=format&fit=crop"],
    cupos: 6,
    duracionMinutos: 45,
  },
  {
    name: "Perfilado de Barba",
    description: "Definición y limpieza de los bordes de la barba con navaja y máquina. Perfecto para mantener el contorno de mejillas, cuello y bigote bien definido.",
    price: 10000,
    category: "Barba",
    imageUrls: ["https://images.unsplash.com/photo-1587909209111-5097ee578ec3?w=800&q=80&auto=format&fit=crop"],
    cupos: 10,
    duracionMinutos: 20,
  },
  {
    name: "Arreglo y Diseño de Barba",
    description: "Recorte, perfilado y diseño personalizado de la barba según la forma de tu rostro. Incluye hidratación con aceite de argán y aplicación de cera moldeadora.",
    price: 16000,
    category: "Barba",
    imageUrls: ["https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80&auto=format&fit=crop"],
    cupos: 7,
    duracionMinutos: 30,
  },
  {
    name: "Hidratación de Barba",
    description: "Tratamiento intensivo de humectación con mascarilla de aceites naturales. Suaviza la barba, elimina resequedad y picazón, dejando el vello brillante y manejable.",
    price: 14000,
    category: "Barba",
    imageUrls: ["https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=800&q=80&auto=format&fit=crop"],
    cupos: 8,
    duracionMinutos: 20,
  },
  {
    name: "Delineado con Navaja",
    description: "Trazado de líneas perfectas en cuello, mejillas y contorno del bigote usando navaja recta. Para una apariencia impecable entre servicios completos.",
    price: 10000,
    category: "Barba",
    imageUrls: ["https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80&auto=format&fit=crop&sat=-100"],
    cupos: 8,
    duracionMinutos: 25,
  },
  {
    name: "Tinte de Barba",
    description: "Coloración profesional de barba y bigote para cubrir canas o cambiar el tono. Colores naturales y semipermanentes para un resultado discreto o dramático.",
    price: 25000,
    category: "Barba",
    imageUrls: ["https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&q=80&auto=format&fit=crop"],
    cupos: 4,
    duracionMinutos: 40,
    customOptions: [
      { name: "Tono", values: ["Negro", "Castaño oscuro", "Castaño medio", "Castaño claro", "Rubio"] },
    ],
  },
];
