import { ServicioData } from "../../../domain/entities/Servicio";

export const CORTES: ServicioData[] = [
  {
    name: "Corte Clásico",
    description: "Corte tradicional con tijera y máquina. Incluye lavado de cabello, corte a tu gusto y peinado final con productos de acabado.",
    price: 15000,
    category: "Cortes",
    imageUrls: ["/uploads/corte-clasico.jpg"],
    cupos: 8,
    duracionMinutos: 30,
  },
  {
    name: "Fade Degradado",
    description: "Degradado moderno con máquina en distintos niveles. Transición suave del largo al corto con acabado limpio y definido en los bordes.",
    price: 20000,
    category: "Cortes",
    imageUrls: ["/uploads/fade-degradado.jpg"],
    cupos: 6,
    duracionMinutos: 45,
  },
  {
    name: "Skin Fade",
    description: "Degradado extremo al ras de la piel con máquina. Contraste máximo entre la parte superior y los laterales. Ideal para looks atrevidos y modernos.",
    price: 25000,
    category: "Cortes",
    imageUrls: ["/uploads/skin-fade.jpg"],
    cupos: 5,
    duracionMinutos: 50,
    customOptions: [
      { name: "Tipo de fade", values: ["Low fade", "Mid fade", "High fade"] },
    ],
  },
  {
    name: "Corte Texturizado",
    description: "Técnica de tijera para crear volumen y movimiento natural. Perfecto para cabellos gruesos o rizados que necesitan control y estilo sin rigidez.",
    price: 20000,
    category: "Cortes",
    imageUrls: ["/uploads/corte-texturizado.webp"],
    cupos: 7,
    duracionMinutos: 40,
  },
  {
    name: "Undercut",
    description: "Rapado total en los laterales con largo conservado en la parte superior. Versátil y elegante, permite peinados hacia atrás, a los lados o con cresta.",
    price: 22000,
    category: "Cortes",
    imageUrls: ["/uploads/undercut.jpg"],
    cupos: 6,
    duracionMinutos: 45,
  },
  {
    name: "Corte Militar",
    description: "Corte corto y uniforme en toda la cabeza. Práctico, fácil de mantener y de aspecto pulcro. Incluye delineado de nuca y orejas.",
    price: 12000,
    category: "Cortes",
    imageUrls: ["/uploads/corte-militar.jpg"],
    cupos: 10,
    duracionMinutos: 25,
  },
  {
    name: "Mohicano Moderno",
    description: "Franja central conservada con laterales rapados o muy degradados. Puedes llevarlo con cresta clásica o con volumen natural para un look urbano.",
    price: 22000,
    category: "Cortes",
    imageUrls: ["https://images.unsplash.com/photo-1542744094-24638eff58bb?w=800&q=80&auto=format&fit=crop"],
    cupos: 5,
    duracionMinutos: 45,
  },
];
